name: Update readme image caches

on:
  schedule:
    # 12:00 Midnight IST converts to 18:30 (6:30 PM) UTC of the previous day
    - cron: '30 18 * * *'
  # Allows manual execution of the workflow directly from the Actions tab
  workflow_dispatch: 

jobs:
  purge-camo-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Flush GitHub Camo Cache for Streak Card
        run: |
          echo "Purging GitHub Streaks Card Cache..."
          curl -X PURGE "https://camo.githubusercontent.com/b9a09cb4ab667dd928b16856f513b44cd9d7f844dc2acb4b48df53d8280dc520/68747470733a2f2f73747265616b2d73746174732e64656d6f6c61622e636f6d2f3f757365723d42726174614275696c6473267468656d653d6461726b26686964655f626f726465723d74727565"

      - name: Output Status
        run: echo "All caches successfully purged."